[files]
extend-exclude = [
    "fmt",
    "minhook",
    "pybind11",
    "LICENSE",
    ".typos.toml"
]

[default.extend-identifiers]
llibgcc_s_seh = "llibgcc_s_seh"

[default.extend-words]
UE = "UE"
