[files]
extend-exclude = [
    "fmt",
    "minhook",
    "pybind11",
    "LICENSE",
    ".typos.toml"
]

[default]
extend-ignore-re = [
    # Ignore markdown links to github commits/trees
    "\\[[0-9a-fA-F]+?\\]\\(https://github.com/.+?/.+?/(commit|tree)/.+?\\)",
    # Ignore a few of the item names from `pick_release_name.py`
    "\"Destructo Spinner\",",
    "\"Sacrificial Skeep\",",
    "\"Skeep Prod\",",
]

[default.extend-identifiers]
llibgcc_s_seh = "llibgcc_s_seh"

[default.extend-words]
UE = "UE"
